# Generated by Django 5.0.4 on 2024-07-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='institution',
        ),
    ]
