# Generated by Django 5.0.3 on 2024-04-08 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_community_post_reply_delete_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='poster_image',
            field=models.ImageField(default=0, upload_to='media/posters/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='community',
            name='categories',
            field=models.ManyToManyField(related_name='communities', to='core.communitycategory'),
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='institution_logos/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(related_name='institution_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='project_files/')),
                ('level', models.CharField(choices=[('Bachelor', 'Bachelor Degree'), ('Masters', "Master's Degree"), ('PhD', 'PhD')], max_length=20)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('total_downloads', models.PositiveIntegerField(default=0)),
                ('institution', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
