# Generated by Django 5.0.4 on 2024-07-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
