# Generated by Django 5.0.4 on 2024-09-09 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_image_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.institution'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated list of tags', max_length=255),
        ),
    ]
