# Generated by Django 5.0.4 on 2024-05-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_article_is_approved_comment_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='poster_image',
            field=models.ImageField(default=0, upload_to='media/course/posters/'),
            preserve_default=False,
        ),
    ]
