# Generated by Django 5.0.4 on 2024-06-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_institution_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('spoc', 'SPOC')], default='regular', max_length=20),
        ),
    ]
