# Generated by Django 5.0.4 on 2024-07-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_studentcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('mooc', 'Mooc'), ('spoc', 'SPOC')], default='regular', max_length=20),
        ),
    ]
