# Generated by Django 4.1.2 on 2024-03-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id_onetimepassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='code',
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='otp',
            field=models.CharField(default=34, max_length=6),
            preserve_default=False,
        ),
    ]
