# Generated by Django 5.0.3 on 2024-03-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('institution_admin', 'Institution Admin'), ('system_admin', 'System Admin')], default='user', max_length=50),
        ),
    ]
